# api/config/packages/api_platform.yaml
api_platform:

    # The title of the API.
    title: 'Stellar API'

    # The description of the API.
    description: 'Stellar REST API'

    # The version of the API.
    version: '1.0.0'

    mapping:
        # The list of paths with files or directories where the bundle will look for additional resource files.
        paths: []

    # The list of your resources class directories. Defaults to the directories of the mapping paths but might differ.
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'

    # The list of enabled formats. The first one will be the default.
    formats:
        #jsonld:
        #    mime_types: ['application/ld+json']

        json:
            mime_types: ['application/json']

        html:
            mime_types: ['text/html']

        # ...

    # The list of enabled error formats. The first one will be the default.
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']

        jsonld:
            mime_types: ['application/ld+json']