jwt_private_key_path: '%kernel.root_dir%/../config/jwt/private.pem'
jwt_public_key_path:  '%kernel.root_dir%/../config/jwt/public.pem'
jwt_key_pass_phrase:  '82ea4855855c8d3f7a38d5bdcc199af5'
jwt_token_ttl:        3600