jwt_private_key_path: '%kernel.root_dir%/../config/jwt/private.pem'
jwt_public_key_path:  '%kernel.root_dir%/../config/jwt/public.pem'
jwt_key_pass_phrase:  '82ea4855855c8d3f7a38d5bdcc199af5'
jwt_token_ttl:        3600

lexik_jwt_authentication:
    # ssh private key path
    private_key_path:    '%kernel.root_dir%/../config/jwt/private.pem'
    # ssh public key path
    public_key_path:     '%kernel.root_dir%/../config/jwt/public.pem'
    # ssh key pass phrase
    pass_phrase:         ''
    # token ttl
    token_ttl:           3600
    # key under which the user identity will be stored in the token payload
    user_identity_field: username

    # token encoding/decoding settings
    encoder:
        # token encoder/decoder service - default implementation based on the namshi/jose library
        service:            lexik_jwt_authentication.encoder.default
        # crypto engine used by the encoder service
        crypto_engine:  openssl
        # encryption algorithm used by the encoder service
        signature_algorithm: RS256

    # token extraction settings
    token_extractors:
        authorization_header:      # look for a token as Authorization Header
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:                    # check token in a cookie
            enabled: false
            name:    BEARER
        query_parameter:           # check token in query string parameter
            enabled: false
            name:    bearer